### PR TITLE
Flutter 3.0.5

### PR DESCRIPTION
**Pull request by majidfathi69**
Basic changes to make the package work on Flutter 3.0.5

### CODE REVIEW

**Review by kuyazee — APPROVED** [review]
works on my end

 please merge if possible

**Comment by AyonAB** [comment]
Will look into it this weekend.

**Comment by rsyd29** [comment]
Nothing works with my project, when calling signalR.connect() and in console it just returns [OkHttp] sendRequest<<

**Comment by AyonAB** [comment]
#45 will supersede this PR.

**Pull request closed without merging**
